version: '3.8'  
services:
  db:  
    container_name: pg_container  
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root  
    ports:  
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - mynetwork
      
networks:
  mynetwork:
    driver: bridge
