version: '3.8'  
services:  
  logging_ms:
    container_name: t2_tp_logging_ms
    image: t2_tp_logging_ms
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - mynetwork
    restart: always
  
  users_ms:
    container_name: t2_tp_users_ms
    image: t2_tp_users_ms
    ports:
      - "127.0.0.1:8020:8020"
    networks:
      - mynetwork
    restart: always
  
  t2_tp_predictions_ms:
    container_name: t2_tp_predictions_ms
    image: t2_tp_predictions_ms
    ports:
      - "127.0.0.1:8010:8010"
    networks:
      - mynetwork
    restart: always
  
  t2_tp_gateway_ms:
    container_name: t2_tp_gategay_ms
    image: t2_tp_gategay_ms
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - mynetwork
    restart: always
  
networks:
  mynetwork:
    driver: bridge
