version: '3.8'  
services:
  db:  
    container_name: pg_container  
    image: postgres  
    restart: always  
    environment:  
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root  
    ports:  
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    networks:
      - mynetwork

  rabbitmqServer:
    container_name: rabbitmqServer
    image: "rabbitmq:3.6-management-alpine"
    hostname: "rabbitmqServer"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
    networks:
      - mynetwork

  logging_ms:
    container_name: t2_tp_logging_ms
    image: marianocarreiracorvel/t2_tp_logging_ms:version1
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    restart: always
    environment:
      FLASK_ENV: "docker"

  users_ms:
    container_name: t2_tp_users_ms
    image: marianocarreiracorvel/t2_tp_users_ms:latest
    ports:
      - "8020:8020"
    networks:
      - mynetwork
    restart: always
    environment:
      FLASK_ENV: "docker"

  t2_tp_predictions_ms:
    container_name: t2_tp_predictions_ms
    image: marianocarreiracorvel/t2_tp_predictions_ms:version1
    ports:
      - "8010:8010"
    networks:
      - mynetwork
    restart: always

  t2_tp_gateway_ms:
    container_name: t2_tp_gategay_ms
    image: marianocarreiracorvel/t2_tp_gategay_ms:version1
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    restart: always
    environment:
      FLASK_ENV: "docker"
  
networks:
  mynetwork:
    driver: bridge
