"""first migration

Revision ID: b0b7280b226f
Revises: 
Create Date: 2024-01-04 18:06:07.022334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b7280b226f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apiKey', sa.Text(), nullable=False),
    sa.Column('suscriptionName', sa.Text(), nullable=False),
    sa.Column('suscriptionRpm', sa.Integer(), nullable=False),
    sa.CheckConstraint('"suscriptionName" IN (\'FREEMIUM\', \'PREMIUM\')', name='check_valid_subscription'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
